### ISSUE TITLE
npm run start 报错

### ISSUE THREAD

**Issue by 910758447** [zhuangyanyan/my-vue#1]

**Comment by 910758447** [comment]
npm run start

**Comment by flyfox11** [comment]
因为这个需要后端数据库支持，所以需要先配置安装数据库，才能运行成功的，由于我的疏漏，不好意思，后续会说明的。

**Comment by jerkruo** [comment]
npm run start 报错了`SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ruo/Desktop/venture-management/server/routes/user/index.js:1:81)
`
